services:
  - type: web
    name: letsfiohub-api
    runtime: python
    repo: https://github.com/kewin228/letsfiohub
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
      - key: SECRET_KEY
        value: letsfiohub-secret-key-2024
